version: '2'
services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 --reload app.app:app  # 使用 gunicorn 并且添加 --reload
    volumes:
      - .:/app
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app/app.py
      # - TZ=Asia/Shanghai
    depends_on:
      - redis
    networks:
      - flaskservice
  redis:
    image: "redis:alpine"
    volumes:
      - ./data:/data
    networks:
      - flaskservice
networks:
  flaskservice:
    driver: bridge